#ifndef CONSTANTS_H
#define CONSTANTS_H

// Display Constants
#define SEPARATOR_WIDTH 3
#define DEFAULT_COL_WIDTH 12
#define COLOR_PAIR_HEADER 1

// Highlighting mode
#define USE_INVERTED_HIGHLIGHT 1  // Use inverted colors for row/column highlighting

// Buffer Sizes
#define DEFAULT_BUFFER_SIZE 8192
#define MAX_COLS 256
#define DEFAULT_MAX_FIELD_LEN 1024
#define DEFAULT_MAX_COLUMN_WIDTH 16
#define DEFAULT_MIN_COLUMN_WIDTH 4

// Cache Constants  
#define DEFAULT_CACHE_SIZE 16384
#define DEFAULT_CACHE_STRING_POOL_SIZE (16 * 1024 * 1024) // 16MB
#define DEFAULT_INTERN_TABLE_SIZE 16384
#define DEFAULT_MAX_TRUNCATED_VERSIONS 8

// File I/O Constants
#define DEFAULT_DELIMITER_SAMPLE_SIZE 1024
#define DEFAULT_LINE_SAMPLE_SIZE 4096
#define DEFAULT_CHARS_PER_LINE 80

// Analysis Constants
#define DEFAULT_COLUMN_ANALYSIS_LINES 1000
#define DEFAULT_CACHE_THRESHOLD_LINES 500
#define DEFAULT_CACHE_THRESHOLD_COLS 50

// Hash Constants (FNV-1a)
#define FNV_OFFSET_BASIS 0x811c9dc5
#define FNV_PRIME 0x01000193

// UI Constants
#define LOG_TIME_BUFFER_SIZE 26
#define CONFIG_LINE_BUFFER_SIZE 256

// Help Screen Layout Constants
#define HELP_COMMANDS_ROW 10
#define HELP_FEATURES_ROW 14
#define HELP_INDENT_COL 2
#define HELP_ITEM_INDENT_COL 4

#endif // CONSTANTS_H 